# Generated by Django 3.1.7 on 2021-05-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Save the name of the input image.', max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='input_image/')),
            ],
        ),
    ]
